Repository PX4/PX4-ECL, pull requests merged in 2019-12, with the labels that each got.

#674 EKF: use Matrix cross product
  EKF/control.cpp
  EKF/ekf.cpp
  EKF/ekf_helper.cpp
  EKF/estimator_interface.cpp
  EKF/estimator_interface.h
  EKF/optflow_fusion.cpp
  EKF/terrain_estimator.cpp
Labels: ekf

#687 Clean initialiseFilter function
  EKF/ekf.cpp
  EKF/ekf.h
Labels: non-functional

#690 Revert if statement swap in resetMagHeading
  EKF/ekf_helper.cpp
Labels: bug
