Repository PX4/PX4-ECL, pull requests merged in 2020-06, with the labels that each got.

#831 EKF: Reduce EKF-GSF vulnerability to large yaw gyro bias errors
  EKF/EKFGSF_yaw.cpp
  EKF/EKFGSF_yaw.h
  EKF/ekf_helper.cpp
Labels: ekf, enhancement

#839 Terrain estimate: Added height above ground source bitmask
  EKF/common.h
  EKF/ekf.h
  EKF/estimator_interface.h
  EKF/terrain_estimator.cpp
Labels: enhancement, non-functional

#842 AlphaFilter: prevent setParameters division by zero
  EKF/AlphaFilter.hpp
Labels: bug

#847 Extract general functions into utils
  EKF/CMakeLists.txt
  EKF/EKFGSF_yaw.cpp
  EKF/EKFGSF_yaw.h
  EKF/drag_fusion.cpp
  EKF/ekf.h
  EKF/ekf_helper.cpp
  EKF/estimator_interface.h
  EKF/mag_fusion.cpp
  EKF/optflow_fusion.cpp
  EKF/sideslip_fusion.cpp
  EKF/terrain_estimator.cpp
  EKF/utils.cpp
  EKF/utils.hpp
Labels: non-functional
