Repository PX4/PX4-ECL, pull requests merged in 2020-07, with the labels that each got.

#859 Return type of resets
  EKF/ekf.h
  EKF/ekf_helper.cpp
Labels: non-functional

#865 Fix firmware-build-test
  .github/workflows/firmware_build_test.yml
Labels: CI

#872 Refactor ev fusion start into helper functions
  EKF/control.cpp
  EKF/ekf.h
  EKF/ekf_helper.cpp
Labels: non-functional

#878 AlphaFilter: include float.h for FLT_EPSILON
  AlphaFilter/AlphaFilter.hpp
Labels: bug

#870 EKF: replacement of covariance prediction autocode with sympy generated output
  EKF/covariance.cpp
  EKF/python/ekf_derivation/__init__.py
  EKF/python/ekf_derivation/code_gen.py
  EKF/python/ekf_derivation/generated/covariance_generated.cpp
  EKF/python/ekf_derivation/generated/covariance_generated_compare.cpp
  EKF/python/ekf_derivation/main.py
  EKF/utils.hpp
  test/CMakeLists.txt
  test/change_indication/iris_gps.csv
  test/test_EKF_utils.cpp
Labels: ekf, enhancement
