Repository PX4/PX4-ECL, pull requests merged in 2021-07, with the labels that each got.

#1019 EKF: Fix clang-tidy complaint
  EKF/drag_fusion.cpp
Labels: non-functional

#1023 EKF: initialize vertical position and velocity variables
  EKF/ekf.h
Labels: bug, ekf

#1027 CI: update container version
  .github/workflows/build_tests.yml
  .github/workflows/firmware_build_test.yml
  .github/workflows/format_checks.yml
  .github/workflows/functional_change_indicator.yml
  .github/workflows/unit_tests.yml
  .github/workflows/update_change_indicator.yml
Labels: CI
